apiVersion: v1
kind: Pod
metadata:
  name: socrata-mcp-server
  labels:
    app: socrata-mcp-server
spec:
  containers:
    - name: socrata-mcp-server
      image: ghcr.io/nyu-rts/socrata-mcp-server:sha-a896f040a4de976e86a6a70abf8dd9ca5630b314
      ports:
        - containerPort: 8000
      resources:
        requests:
          cpu: 250m
          memory: 256M
        limits:
          cpu: "1"
          memory: 512M
